### ISSUE TITLE
Release into the ROS buildfarm

### ISSUE THREAD

**Issue by esteve** [lgsvl/lgsvl_msgs#1]
It'd be great if this package were released into the ROS buildfarm so it could be installed via rosdep (e.g. apt-get). [bloom](https://wiki.ros.org/bloom) makes it easy to push it to ROS. Let me know if there's anything I can help with.

**Comment by daviduhm** [comment]
@esteve Thanks for pointing it out! Currently, this task is on our to-do list and the package will be released to the ROS build farm soon.

**Comment by esteve** [comment]
@daviduhm I'd be very happy to help with that. Here's a guide in case you'd like to know more about what the process is like (it's fairly straightforward thanks to bloom):

https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by daviduhm** [comment]
@esteve Our PR for the release has already been merged by one of the ROS developers. It'll be released into the building repository and synchronized over to the public ROS debian repositories soon!
